"""Add Battles

Revision ID: 33ae8f36f7ee
Revises: 2f812a5fe98f
Create Date: 2025-02-23 12:14:18.680944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ae8f36f7ee'
down_revision: Union[str, None] = '2f812a5fe98f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
